find_path(QGLVIEWER_INCLUDE_DIR
  QGLViewer/qglviewer.h)
find_library(QGLVIEWER_LIBRARY
  NAMES
    QGLViewer2
    QGLViewer)

set(QGLVIEWER_INCLUDE_DIRS "${QGLVIEWER_INCLUDE_DIR}")
set(QGLVIEWER_LIBRARIES "${QGLVIEWER_LIBRARY}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QGLViewer
  REQUIRED_VARS
    QGLVIEWER_INCLUDE_DIR
    QGLVIEWER_LIBRARY)

mark_as_advanced(
  QGLVIEWER_INCLUDE_DIR
  QGLVIEWER_LIBRARY)

if(QGLVIEWER_FOUND AND NOT TARGET QGLViewer::QGLViewer)
  add_library(QGLViewer::QGLViewer INTERFACE IMPORTED)
  set_target_properties(QGLViewer::QGLViewer PROPERTIES
    INTERFACE_LINK_LIBRARIES "${QGLVIEWER_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${QGLVIEWER_INCLUDE_DIR}")
endif()
